name: 'H-W'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '03 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  H:
    runs-on: self-hosted
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
        - name: ' Environment Settings'
          run: |
            apt update
            apt install chromium-browser ffmpeg python3-pip -y
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
            pip3 install selenium==4.2.0            
        - name: 'Renew-H'
          env:
            URL_BASE: ${{ secrets.URL_BASE_H }}
            USER_ID: ${{ secrets.USER_ID_18 }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}

          run: |
            python3 ./main.py
            
  W:
    runs-on: self-hosted
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
        - name: ' Environment Settings'
          run: |
            apt update
            apt install chromium-browser ffmpeg python3-pip -y
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
            pip3 install selenium==4.2.0    
        - name: 'Renew-W'
          env:
            URL_BASE: ${{ secrets.URL_BASE_W }}
            USER_ID: ${{ secrets.USER_ID_18 }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}

          run: |
            python3 ./main.py
